version: '3.8'

services:
  wtp_bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - ENVIRONMENT=production
      - VKONTAKTE_TOKEN=${VKONTAKTE_TOKEN}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    restart: unless-stopped
